language: node_js
os:
  - linux
node_js:
  - 6
before_install:
  - npm install -g npm@5.1.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  global:
    - CXX=g++-4.9
  matrix:
    - NPM_COMMAND=tsc
    - NPM_COMMAND=lint
    - NPM_COMMAND=test
notifications:
  email: false
script: npm run $NPM_COMMAND
after_success: npm run coveralls
